### ISSUE TITLE
Mapa Mental 

### ISSUE THREAD

**Issue by LeinnaMora** [SistemasTecTlaxiaco/actividad-4-mapa-mental-LeinnaMora#2]
[MapaMental_GonzalezMoralesLeidaly.pdf](https://github.com/user-attachments/files/17085674/MapaMental_GonzalezMoralesLeidaly.pdf)

**Comment by josealfredo79** [comment]
Calificacion...?

**Comment by W1ll1am21** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
